# command line: main.py --config config/nturgbd120-cross-subject/default_long.yaml --model model.baseline.Model --work-dir work_dir/ntu120/csub/baseline --device 4 --start-epoch 65 --weights work_dir/ntu120/csub/baseline/runs-65-63960.pt

base_lr: 0.1
batch_size: 64
config: config/nturgbd120-cross-subject/default_long.yaml
device:
- 4
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.baseline.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 120
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 110
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 65
step:
- 35
- 55
- 90
- 100
test_batch_size: 64
test_feeder_args:
  bone: false
  data_path: data/ntu120/NTU120_CSub.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/ntu120/NTU120_CSub.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: work_dir/ntu120/csub/baseline/runs-65-63960.pt
work_dir: work_dir/ntu120/csub/baseline
