# command line: main.py --config work_dir/cset/local_SHTg_bonevel/config.yaml --model model.local_SHTg.Model --work-dir work_dir/cset/local_SHTg_bonevel --device 3 --phase train --start-epoch 39 --weights work_dir/cset/local_SHTg_bonevel/runs-39-33189.pt

base_lr: 0.1
batch_size: 64
config: work_dir/cset/local_SHTg_bonevel/config.yaml
device:
- 3
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.local_SHTg.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 120
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 65
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 39
step:
- 35
- 55
test_batch_size: 64
test_feeder_args:
  bone: true
  data_path: data/ntu120/NTU120_CSet.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: true
  window_size: 64
train_feeder_args:
  bone: true
  data_path: data/ntu120/NTU120_CSet.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: true
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: work_dir/cset/local_SHTg_bonevel/runs-39-33189.pt
work_dir: work_dir/cset/local_SHTg_bonevel
